meson: drop DATADIR from config.h
As it creates conflicts with windows compilers, resulting in strange
errors:

In file included from ../src/as-utils.c:25:
./config.h:16:17: error: expected identifier or '(' before string constant
   16 | #define DATADIR "/usr/x86_64-w64-mingw32/sys-root/mingw/share"
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Marc-André Lureau <marcandre.lureau@redhat.com>