meson: Pass -D_DARWIN_C_SOURCE on darwin
This is probably a follow-up for 02ee2d0daa ("fix macos build")
and unbreaks the build on Nixpkgs x86_64-darwin, probably due to
using even older SDKs?

https://github.com/NixOS/nixpkgs/runs/19486840382

```
> In file included from ../src/as-system-info.c:60:
> In file included from /nix/store/51c1k4sj0irwgyvkgbyhqi0ggilyh3j2-Libsystem-1238.60.2/include/sys/sysctl.h:83:
> /nix/store/51c1k4sj0irwgyvkgbyhqi0ggilyh3j2-Libsystem-1238.60.2/include/sys/ucred.h:91:2: error: unknown type name 'u_long'
>         u_long  cr_ref;                 /* reference count */
>         ^
> 1 error generated.
> ninja: build stopped: subcommand failed.
```

Instead of adding another typedef, apply the suggestions on pull
request 556 to pass `-D_DARWIN_C_SOURCE`, which seems to work fine
for us too.